from __future__ import annotations

from app.domain.classification import SensitivityLevel
from app.domain.identity import UserRole
from app.domain.policy import PolicyDecision
from app.policy.rules import PolicyRule


def default_policy_rules() -> tuple[PolicyRule, ...]:
    any_governance_role = (
        UserRole.DATA_STEWARD,
        UserRole.DATA_OWNER,
        UserRole.DATA_ENGINEER,
        UserRole.DATA_ANALYST,
        UserRole.SECURITY_REVIEWER,
        UserRole.GOVERNANCE_ADMIN,
        UserRole.AGENT_SERVICE,
        UserRole.READONLY_AUDITOR,
    )
    return (
        PolicyRule(
            rule_id="default.allow_metadata_query",
            name="Allow metadata query",
            description="Metadata queries are allowed for governed runtime roles.",
            effect=PolicyDecision.ALLOW,
            priority=100,
            match_operations=("metadata.query",),
            match_asset_types=("metadata",),
            match_roles=any_governance_role,
            reason="Metadata query is allowed.",
        ),
        PolicyRule(
            rule_id="default.allow_metric_definition_query",
            name="Allow metric definition query",
            description="Metric definition lookup is allowed for governed runtime roles.",
            effect=PolicyDecision.ALLOW,
            priority=110,
            match_operations=("metric.definition.query",),
            match_asset_types=("metric_definition", "metric"),
            match_roles=any_governance_role,
            reason="Metric definition query is allowed.",
        ),
        PolicyRule(
            rule_id="default.allow_table_metadata_query",
            name="Allow table metadata query",
            description="Table metadata inspection is allowed for governed runtime roles.",
            effect=PolicyDecision.ALLOW,
            priority=115,
            match_operations=("table_metadata.query",),
            match_asset_types=("metadata", "table"),
            match_roles=any_governance_role,
            reason="Table metadata query is allowed.",
        ),
        PolicyRule(
            rule_id="default.allow_aggregate_metric_query",
            name="Allow aggregate metric query",
            description="Aggregate metric query is allowed when it does not request L4/L5 data.",
            effect=PolicyDecision.ALLOW,
            priority=120,
            match_operations=("metric.aggregate.query",),
            match_asset_types=("aggregate_metric", "metric"),
            match_roles=any_governance_role,
            reason="Aggregate metric query is allowed.",
        ),
        PolicyRule(
            rule_id="default.allow_quality_rule_suggestion",
            name="Allow quality rule suggestion",
            description="Generating quality-rule suggestions is allowed.",
            effect=PolicyDecision.ALLOW,
            priority=125,
            match_operations=("quality_rule.suggest",),
            match_asset_types=("quality_rule", "table"),
            match_roles=any_governance_role,
            reason="Quality rule suggestion is allowed.",
        ),
        PolicyRule(
            rule_id="default.allow_quality_check_run",
            name="Allow quality check",
            description="Running quality checks is allowed.",
            effect=PolicyDecision.ALLOW,
            priority=126,
            match_operations=("quality_check.run",),
            match_asset_types=("quality_rule", "table"),
            match_roles=any_governance_role,
            reason="Quality check is allowed.",
        ),
        PolicyRule(
            rule_id="default.allow_column_profile_query",
            name="Allow safe column profile",
            description=(
                "Safe column profiling is allowed when plaintext samples are not returned."
            ),
            effect=PolicyDecision.ALLOW,
            priority=126,
            match_operations=("column_profile.query",),
            match_asset_types=("column", "metadata"),
            match_roles=any_governance_role,
            reason="Safe column profile query is allowed.",
        ),
        PolicyRule(
            rule_id="default.allow_lineage_query",
            name="Allow lineage query",
            description="Lineage query is allowed for governed catalog assets.",
            effect=PolicyDecision.ALLOW,
            priority=126,
            match_operations=("lineage.query",),
            match_asset_types=("lineage", "table"),
            match_roles=any_governance_role,
            reason="Lineage query is allowed.",
        ),
        PolicyRule(
            rule_id="default.allow_sensitivity_classification",
            name="Allow sensitivity classification",
            description="Sensitivity classification is allowed.",
            effect=PolicyDecision.ALLOW,
            priority=127,
            match_operations=("sensitivity.classify",),
            match_asset_types=("metadata", "column", "security"),
            match_roles=any_governance_role,
            reason="Sensitivity classification is allowed.",
        ),
        PolicyRule(
            rule_id="default.allow_permission_check",
            name="Allow permission check",
            description="Permission inspection is allowed.",
            effect=PolicyDecision.ALLOW,
            priority=128,
            match_operations=("permission.check",),
            match_asset_types=("permission", "security"),
            match_roles=any_governance_role,
            reason="Permission check is allowed.",
        ),
        PolicyRule(
            rule_id="default.allow_metric_card_generate",
            name="Allow metric card generation",
            description="Generating a metric card is allowed.",
            effect=PolicyDecision.ALLOW,
            priority=129,
            match_operations=("metric.card.generate",),
            match_asset_types=("metric_definition", "metric"),
            match_roles=any_governance_role,
            reason="Metric card generation is allowed.",
        ),
        PolicyRule(
            rule_id="default.allow_sql_gateway_query",
            name="Allow SQL Gateway review",
            description="SQL query requests may proceed only to SQL Gateway review.",
            effect=PolicyDecision.ALLOW,
            priority=130,
            match_tool_names=("query_sql",),
            match_operations=("sql.query",),
            match_asset_types=("sql_query", "aggregate_metric", "table"),
            match_roles=any_governance_role,
            reason="SQL query may proceed to SQL Gateway review.",
        ),
        PolicyRule(
            rule_id="default.deny_l3_detail_query",
            name="Deny L3 detail query",
            description="L3 detail data cannot be queried by the agent runtime.",
            effect=PolicyDecision.DENY,
            priority=10,
            match_operations=("data.detail.query", "sql.detail.query"),
            match_asset_types=("table", "column", "detail"),
            match_sensitivity_levels=(SensitivityLevel.L3,),
            reason="L3 detail data query is denied.",
        ),
        PolicyRule(
            rule_id="default.deny_l4_l5",
            name="Deny L4 and L5 data",
            description="L4 and L5 data are denied for all tool calls.",
            effect=PolicyDecision.DENY,
            priority=5,
            match_sensitivity_levels=(SensitivityLevel.L4, SensitivityLevel.L5),
            reason="L4/L5 data access is denied.",
        ),
        PolicyRule(
            rule_id="default.ask_create_quality_rule",
            name="Ask before creating quality rule",
            description="Creating data quality rules requires governance review.",
            effect=PolicyDecision.ASK,
            priority=200,
            match_operations=("quality_rule.create",),
            match_asset_types=("quality_rule",),
            reason="Creating quality rules requires approval.",
        ),
        PolicyRule(
            rule_id="default.ask_modify_masking_policy",
            name="Ask before modifying masking policy",
            description="Masking policy changes require security review.",
            effect=PolicyDecision.ASK,
            priority=210,
            match_operations=("masking_policy.modify",),
            match_asset_types=("masking_policy", "policy"),
            reason="Modifying masking policy requires approval.",
        ),
        PolicyRule(
            rule_id="default.deny_delete_data",
            name="Deny data deletion",
            description="The agent runtime cannot delete data.",
            effect=PolicyDecision.DENY,
            priority=1,
            match_operations=("data.delete", "sql.delete"),
            reason="Deleting data is denied.",
        ),
        PolicyRule(
            rule_id="default.deny_bypass_masking",
            name="Deny masking bypass",
            description="The agent runtime cannot bypass DLP or masking.",
            effect=PolicyDecision.DENY,
            priority=1,
            match_operations=("masking.bypass", "dlp.bypass"),
            reason="Bypassing masking is denied.",
        ),
        PolicyRule(
            rule_id="default.deny_disable_audit",
            name="Deny audit shutdown",
            description="The agent runtime cannot disable audit logging.",
            effect=PolicyDecision.DENY,
            priority=1,
            match_operations=("audit.disable", "audit.shutdown"),
            reason="Disabling audit is denied.",
        ),
    )
