"""Connector abstractions and mock adapters for external governance systems."""

from app.connectors.base import (
    BaseConnector,
    ConnectorCallContext,
    ConnectorConfig,
    ConnectorError,
    ConnectorKind,
    ConnectorSecurityError,
    ConnectorTimeoutError,
    ConnectorUnavailableError,
    StubConnector,
)
from app.connectors.interfaces import (
    LineageConnector,
    MaskingConnector,
    MetadataConnector,
    MetricConnector,
    PermissionConnector,
    QualityConnector,
    SchedulerConnector,
    WarehouseConnector,
    WorkflowConnector,
)
from app.connectors.mocks import (
    MockLineageConnector,
    MockMaskingConnector,
    MockMetadataConnector,
    MockMetricConnector,
    MockPermissionConnector,
    MockQualityConnector,
    MockSchedulerConnector,
    MockWarehouseConnector,
    MockWorkflowConnector,
    build_mock_connectors,
)
from app.connectors.stubs import (
    AtlasLineageConnector,
    DLPMaskingConnector,
    IAMPermissionConnector,
    MetricPlatformConnector,
    OpenMetadataConnector,
    QualityPlatformConnector,
    TicketWorkflowConnector,
    WarehouseEngineConnector,
    WorkflowSchedulerConnector,
)

__all__ = [
    "AtlasLineageConnector",
    "BaseConnector",
    "ConnectorCallContext",
    "ConnectorConfig",
    "ConnectorError",
    "ConnectorKind",
    "ConnectorSecurityError",
    "ConnectorTimeoutError",
    "ConnectorUnavailableError",
    "DLPMaskingConnector",
    "IAMPermissionConnector",
    "LineageConnector",
    "MaskingConnector",
    "MetadataConnector",
    "MetricConnector",
    "MetricPlatformConnector",
    "MockLineageConnector",
    "MockMaskingConnector",
    "MockMetadataConnector",
    "MockMetricConnector",
    "MockPermissionConnector",
    "MockQualityConnector",
    "MockSchedulerConnector",
    "MockWarehouseConnector",
    "MockWorkflowConnector",
    "OpenMetadataConnector",
    "PermissionConnector",
    "QualityConnector",
    "QualityPlatformConnector",
    "SchedulerConnector",
    "StubConnector",
    "TicketWorkflowConnector",
    "WarehouseConnector",
    "WarehouseEngineConnector",
    "WorkflowConnector",
    "WorkflowSchedulerConnector",
    "build_mock_connectors",
]
