"""Connector abstractions and real adapters for external governance systems."""

from app.connectors.base import (
    BaseConnector,
    ConnectorCallContext,
    ConnectorConfig,
    ConnectorError,
    ConnectorKind,
    ConnectorSecurityError,
    ConnectorTimeoutError,
    ConnectorUnavailableError,
    StubConnector,
)
from app.connectors.factory import (
    UnconfiguredMetadataConnector,
    UnconfiguredWarehouseConnector,
    build_metadata_connector_from_env,
    build_warehouse_connector_from_env,
)
from app.connectors.interfaces import (
    LineageConnector,
    MaskingConnector,
    MetadataConnector,
    MetricConnector,
    PermissionConnector,
    QualityConnector,
    SchedulerConnector,
    WarehouseConnector,
    WorkflowConnector,
)
from app.connectors.secrets import EnvSecretProvider, SecretResolutionError, StarRocksCredentials
from app.connectors.starrocks import StarRocksMetadataConnector, StarRocksWarehouseConnector
from app.connectors.stubs import (
    AtlasLineageConnector,
    DLPMaskingConnector,
    IAMPermissionConnector,
    MetricPlatformConnector,
    OpenMetadataConnector,
    QualityPlatformConnector,
    TicketWorkflowConnector,
    WarehouseEngineConnector,
    WorkflowSchedulerConnector,
)

__all__ = [
    "AtlasLineageConnector",
    "BaseConnector",
    "ConnectorCallContext",
    "ConnectorConfig",
    "ConnectorError",
    "ConnectorKind",
    "ConnectorSecurityError",
    "ConnectorTimeoutError",
    "ConnectorUnavailableError",
    "DLPMaskingConnector",
    "EnvSecretProvider",
    "IAMPermissionConnector",
    "LineageConnector",
    "MaskingConnector",
    "MetadataConnector",
    "MetricConnector",
    "MetricPlatformConnector",
    "OpenMetadataConnector",
    "PermissionConnector",
    "QualityConnector",
    "QualityPlatformConnector",
    "SchedulerConnector",
    "SecretResolutionError",
    "StarRocksCredentials",
    "StarRocksMetadataConnector",
    "StarRocksWarehouseConnector",
    "StubConnector",
    "TicketWorkflowConnector",
    "UnconfiguredMetadataConnector",
    "UnconfiguredWarehouseConnector",
    "WarehouseConnector",
    "WarehouseEngineConnector",
    "WorkflowConnector",
    "WorkflowSchedulerConnector",
    "build_metadata_connector_from_env",
    "build_warehouse_connector_from_env",
]
