import type { Translate } from "./types";

const displayLabelKeys: Record<string, string> = {
  dev: "开发",
  test: "测试",
  staging: "预发",
  prod: "生产",
  manager: "管理者",
  data_team: "数据团队",
  operations: "运营团队",
  operation_team: "运营团队",
  agent_runtime: "Agent Runtime",
  low: "低",
  medium: "中",
  high: "高",
  critical: "严重",
  query_sql: "SQL 查询工具",
  search_metadata: "元数据检索工具",
  get_metric_definition: "指标口径工具",
  query_metric: "指标查询",
  explain_metric: "指标解释",
  run_governance_task: "治理任务",
  read_only: "只读",
  metadata_only: "仅元数据",
  mock: "Mock",
  allow: "允许",
  ask: "需审批",
  deny: "拒绝",
  ALLOW: "允许",
  ASK: "需审批",
  DENY: "拒绝",
  complete: "已完成",
  needs_clarification: "需要澄清",
  denied: "已拒答",
  escalated: "已升级",
  planned: "已规划",
  pass: "通过",
  recorded: "已记录",
  masked: "已脱敏",
  blocked: "已阻断",
  none: "无",
  not_applicable: "不适用",
  not_required: "无需审批",
  approval_required: "需要审批",
  plan_required: "需要计划审批",
  active: "已启用",
  draft: "草稿",
  open: "待处理",
  tracking: "跟进中",
  resolved: "已解决",
  investigating: "排查中",
  published: "已发布",
  not_run: "未运行",
  created: "已创建",
  completed: "已完成",
  waiting_approval: "等待审批",
  approved: "已审批通过",
  rejected: "已驳回",
  succeeded: "成功",
  running: "运行中",
  passed: "已通过",
  failed: "未通过",
  data_quality: "数据质量",
  sensitive_data_discovery: "敏感数据识别",
  asset_inventory: "资产盘点",
  data_domain_governance: "数据域治理",
  metadata_completion: "元数据补全",
  metric_governance: "指标口径治理",
  permission_inspection: "权限巡检",
  lineage_impact: "血缘影响分析",
  governance_report: "治理报告",
  request_intake: "任务接入",
  task_classification: "任务分类",
  clarification: "澄清补全",
  asset_mapping: "资产映射",
  governance_planning: "治理规划",
  evidence_collection: "证据采集",
  risk_review: "风险审查",
  result_synthesis: "结果合成",
  knowledge_persist: "知识沉淀",
  pending: "待执行",
  positive: "满意",
  negative: "不满意",
  metric_mismatch: "指标口径不一致",
  value_error: "数值错误",
  permission_error: "权限错误",
  answer_unclear: "回答不清晰",
  select_star: "SELECT * 风险",
  ddl_dml: "DDL / DML 风险",
  ddl_detected: "DDL 风险",
  dml_detected: "DML 风险",
  no_limit: "缺少 LIMIT",
  missing_limit: "缺少 LIMIT",
  sensitive_column: "敏感字段",
  sensitive_field: "敏感字段",
  raw_layer_access: "原始层访问",
  cross_domain_join: "跨域 Join",
  large_result_risk: "大结果集风险",
  unknown_table: "未登记表",
  unsafe_function: "危险函数",
  large_scan: "大扫描量",
  partial_mask: "部分脱敏",
  hash: "哈希",
  redact: "隐藏",
  aggregate_only: "仅聚合展示",
  runtime_release: "Runtime 发布",
  product_release: "产品发布",
  rollback: "回滚",
  semantic_layer: "语义层",
  prompt_skill: "Prompt / Skill",
  policy: "策略",
  sql_gateway: "SQL 网关",
  answer_template: "回答模板",
  case_added: "已加入 Case",
  eval_running: "评测运行中"
};

export function displayLabel(value: unknown, t: Translate): string {
  const text = String(value ?? "");
  if (!text) return "";
  return t(displayLabelKeys[text] ?? text);
}

export function displayJoinedLabels(values: string[] | undefined, t: Translate): string {
  if (!values || values.length === 0) return t("无");
  return values.map((value) => displayLabel(value, t)).join(", ");
}
